"""Generate synthetic contract fixtures for every Phase 2 schema family."""
import json
from pathlib import Path
R=Path(__file__).resolve().parents[1]/"fixtures"/"contracts"
R.mkdir(parents=True,exist_ok=True)
D={
"taxpayer.json":{"country":"HU","entity_type":"sole_proprietor","vat_status_reported":"AAM","eu_vat_number_present":True,"establishment_country":"HU","tax_year":2026,"facts_as_of":"2026-10-08","annual_turnover":None,"turnover_currency":"HUF","source_fact_ids":["synthetic-fact-1"]},
"customer.json":{"country":"DE","business_establishment_country":"DE","customer_type_claimed":"business","business_status":"verified_business","business_status_evidence":["synthetic_valid_vat_id"],"status_evidence_reviewed":True,"vat_id":"SYNTHETIC-DE-001","vat_id_verification":"synthetic_valid","verification_at":"2026-10-08T10:00:00Z","evidence_country_signals":[{"kind":"business_establishment","country":"DE","observed_at":"2026-10-08T10:00:00Z"}]},
"transaction.json":{"service_as_described":"Synthetic maintenance subscription; facts incomplete.","service_classification":"unclassified","classification_basis":[],"classification_reviewed":False,"special_place_of_supply_reviewed":False,"automation_level":"unknown","human_intervention":"unknown","article59c_assessment":"not_assessed","billing_frequency":"monthly","currency":"EUR","price_basis":"unknown","transaction_date":"2026-10-08","tax_point_date":None,"payment_provider":"synthetic-no-connection","amount":10000,"events":[]},
"conclusion.json":{"status":"cannot_determine","reason":"LIVE_VERIFICATION_REQUIRED","statement":"Cannot determine from supplied synthetic facts.","evidence_refs":[],"uncertainty_categories":["MISSING_FACT","LIVE_VERIFICATION_REQUIRED","HUMAN_ACCOUNTANT_DECISION"]},
"review-escalation.json":{"escalate":True,"reasons":["SERVICE_CLASSIFICATION_UNCLEAR","LIVE_STATUS_REQUIRED"],"reviewer_role":"accountant","required_evidence":["Service work description","Current VAT status evidence"],"decision_blocked":True},
"evidence.json":{"source_id":"hu-nav-aam-2026-guidance","provision":"Áfa tv. 188. § (2), as identified in NAV guidance","source_version":"2025-12-11 guidance; applies to stated 2026 point subject to law check","retrieved_at":"2026-10-08","supports":"NAV states 2026 domestic AAM ceiling and eligibility summary","authority_level":"official_guidance","source_url":"https://nav.gov.hu/ado/afa/Emelkedik_az_alanyi_adomentesseg_ertekhatara","quote_or_extract":None,"content_hash":None},
"decision-provenance.json":{"decision_id":"synthetic-decision-001","as_of_date":"2026-10-08","transaction_date":"2026-10-08","facts":{"customer_country":"DE","service":"maintenance as described; not classified"},"assumptions":["All facts are synthetic."],"rules_applied":[],"evidence":[{"source_id":"hu-nav-aam-2026-guidance","provision":"188. § (2) reference only","source_version":"2025-12-11","retrieved_at":"2026-10-08","supports":"Sample evidence link only","authority_level":"official_guidance","source_url":"https://nav.gov.hu/ado/afa/Emelkedik_az_alanyi_adomentesseg_ertekhatara","quote_or_extract":None,"content_hash":None}],"interpretation":"No tax treatment is asserted.","conclusion":{"status":"cannot_determine","reason":"MISSING_FACT","statement":"Synthetic provenance example only.","evidence_refs":["hu-nav-aam-2026-guidance"],"uncertainty_categories":["MISSING_FACT"]},"confidence":"low","requires_human_review":True,"unresolved_questions":["What service was actually performed?"]},
"mcp-request.json":{"request_id":"synthetic-request-001","tool":"tax_analyze_transaction","as_of_date":"2026-10-08","jurisdiction":"HU","payload":{"fixture":"synthetic-only"},"authorization_context":None},
"mcp-response.json":{"request_id":"synthetic-request-001","status":"cannot_determine","result":None,"source_refs":[],"uncertainty_categories":["MISSING_FACT"],"requires_human_review":True,"errors":[],"generated_at":"2026-10-08T10:00:00Z"}
}
for n,v in D.items():(R/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
print(f"Wrote {len(D)} contract fixtures")
